/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutClientesRouteImport } from './routes/_layout/clientes'
import { Route as LayoutComprasRouteImport } from './routes/_layout/compras'
import { Route as LayoutConfiguracionRouteImport } from './routes/_layout/configuracion'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutMultimediaRouteImport } from './routes/_layout/multimedia'
import { Route as LayoutPosRouteImport } from './routes/_layout/pos'
import { Route as LayoutUsuariosRouteImport } from './routes/_layout/usuarios'
import { Route as LayoutVentasRouteImport } from './routes/_layout/ventas'
import { Route as LoginTenantSlugRouteImport } from './routes/login.$tenantSlug'
import { Route as LayoutCajasHistorialRouteImport } from './routes/_layout/cajas/historial'
import { Route as LayoutCajasRegistradorasRouteImport } from './routes/_layout/cajas/registradoras'
import { Route as LayoutInventarioCrearRouteImport } from './routes/_layout/inventario/crear'
import { Route as LayoutInventarioLotesRouteImport } from './routes/_layout/inventario/lotes'
import { Route as LayoutInventarioProductosRouteImport } from './routes/_layout/inventario/productos'
import { Route as LayoutReportesIndexRouteImport } from './routes/_layout/reportes/index'
import { Route as LayoutReportesCostoVentasRouteImport } from './routes/_layout/reportes/costo-ventas'
import { Route as LayoutReportesExistenciasValuadasRouteImport } from './routes/_layout/reportes/existencias-valuadas'
import { Route as LayoutReportesVentasProductosRouteImport } from './routes/_layout/reportes/ventas-productos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutClientesRoute = LayoutClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComprasRoute = LayoutComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfiguracionRoute = LayoutConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMultimediaRoute = LayoutMultimediaRouteImport.update({
  id: '/multimedia',
  path: '/multimedia',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPosRoute = LayoutPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsuariosRoute = LayoutUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVentasRoute = LayoutVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => LayoutRoute,
} as any)
const LoginTenantSlugRoute = LoginTenantSlugRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => LoginRoute,
} as any)
const LayoutCajasHistorialRoute = LayoutCajasHistorialRouteImport.update({
  id: '/cajas/historial',
  path: '/cajas/historial',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCajasRegistradorasRoute =
  LayoutCajasRegistradorasRouteImport.update({
    id: '/cajas/registradoras',
    path: '/cajas/registradoras',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventarioCrearRoute = LayoutInventarioCrearRouteImport.update({
  id: '/inventario/crear',
  path: '/inventario/crear',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventarioLotesRoute = LayoutInventarioLotesRouteImport.update({
  id: '/inventario/lotes',
  path: '/inventario/lotes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventarioProductosRoute =
  LayoutInventarioProductosRouteImport.update({
    id: '/inventario/productos',
    path: '/inventario/productos',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutReportesIndexRoute = LayoutReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportesCostoVentasRoute =
  LayoutReportesCostoVentasRouteImport.update({
    id: '/reportes/costo-ventas',
    path: '/reportes/costo-ventas',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutReportesExistenciasValuadasRoute =
  LayoutReportesExistenciasValuadasRouteImport.update({
    id: '/reportes/existencias-valuadas',
    path: '/reportes/existencias-valuadas',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutReportesVentasProductosRoute =
  LayoutReportesVentasProductosRouteImport.update({
    id: '/reportes/ventas-productos',
    path: '/reportes/ventas-productos',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/clientes': typeof LayoutClientesRoute
  '/compras': typeof LayoutComprasRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/multimedia': typeof LayoutMultimediaRoute
  '/pos': typeof LayoutPosRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/ventas': typeof LayoutVentasRoute
  '/login/$tenantSlug': typeof LoginTenantSlugRoute
  '/cajas/historial': typeof LayoutCajasHistorialRoute
  '/cajas/registradoras': typeof LayoutCajasRegistradorasRoute
  '/inventario/crear': typeof LayoutInventarioCrearRoute
  '/inventario/lotes': typeof LayoutInventarioLotesRoute
  '/inventario/productos': typeof LayoutInventarioProductosRoute
  '/reportes/costo-ventas': typeof LayoutReportesCostoVentasRoute
  '/reportes/existencias-valuadas': typeof LayoutReportesExistenciasValuadasRoute
  '/reportes/ventas-productos': typeof LayoutReportesVentasProductosRoute
  '/reportes/': typeof LayoutReportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/clientes': typeof LayoutClientesRoute
  '/compras': typeof LayoutComprasRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/multimedia': typeof LayoutMultimediaRoute
  '/pos': typeof LayoutPosRoute
  '/usuarios': typeof LayoutUsuariosRoute
  '/ventas': typeof LayoutVentasRoute
  '/login/$tenantSlug': typeof LoginTenantSlugRoute
  '/cajas/historial': typeof LayoutCajasHistorialRoute
  '/cajas/registradoras': typeof LayoutCajasRegistradorasRoute
  '/inventario/crear': typeof LayoutInventarioCrearRoute
  '/inventario/lotes': typeof LayoutInventarioLotesRoute
  '/inventario/productos': typeof LayoutInventarioProductosRoute
  '/reportes/costo-ventas': typeof LayoutReportesCostoVentasRoute
  '/reportes/existencias-valuadas': typeof LayoutReportesExistenciasValuadasRoute
  '/reportes/ventas-productos': typeof LayoutReportesVentasProductosRoute
  '/reportes': typeof LayoutReportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_layout/clientes': typeof LayoutClientesRoute
  '/_layout/compras': typeof LayoutComprasRoute
  '/_layout/configuracion': typeof LayoutConfiguracionRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/multimedia': typeof LayoutMultimediaRoute
  '/_layout/pos': typeof LayoutPosRoute
  '/_layout/usuarios': typeof LayoutUsuariosRoute
  '/_layout/ventas': typeof LayoutVentasRoute
  '/login/$tenantSlug': typeof LoginTenantSlugRoute
  '/_layout/cajas/historial': typeof LayoutCajasHistorialRoute
  '/_layout/cajas/registradoras': typeof LayoutCajasRegistradorasRoute
  '/_layout/inventario/crear': typeof LayoutInventarioCrearRoute
  '/_layout/inventario/lotes': typeof LayoutInventarioLotesRoute
  '/_layout/inventario/productos': typeof LayoutInventarioProductosRoute
  '/_layout/reportes/costo-ventas': typeof LayoutReportesCostoVentasRoute
  '/_layout/reportes/existencias-valuadas': typeof LayoutReportesExistenciasValuadasRoute
  '/_layout/reportes/ventas-productos': typeof LayoutReportesVentasProductosRoute
  '/_layout/reportes/': typeof LayoutReportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/dashboard'
    | '/multimedia'
    | '/pos'
    | '/usuarios'
    | '/ventas'
    | '/login/$tenantSlug'
    | '/cajas/historial'
    | '/cajas/registradoras'
    | '/inventario/crear'
    | '/inventario/lotes'
    | '/inventario/productos'
    | '/reportes/costo-ventas'
    | '/reportes/existencias-valuadas'
    | '/reportes/ventas-productos'
    | '/reportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/dashboard'
    | '/multimedia'
    | '/pos'
    | '/usuarios'
    | '/ventas'
    | '/login/$tenantSlug'
    | '/cajas/historial'
    | '/cajas/registradoras'
    | '/inventario/crear'
    | '/inventario/lotes'
    | '/inventario/productos'
    | '/reportes/costo-ventas'
    | '/reportes/existencias-valuadas'
    | '/reportes/ventas-productos'
    | '/reportes'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/clientes'
    | '/_layout/compras'
    | '/_layout/configuracion'
    | '/_layout/dashboard'
    | '/_layout/multimedia'
    | '/_layout/pos'
    | '/_layout/usuarios'
    | '/_layout/ventas'
    | '/login/$tenantSlug'
    | '/_layout/cajas/historial'
    | '/_layout/cajas/registradoras'
    | '/_layout/inventario/crear'
    | '/_layout/inventario/lotes'
    | '/_layout/inventario/productos'
    | '/_layout/reportes/costo-ventas'
    | '/_layout/reportes/existencias-valuadas'
    | '/_layout/reportes/ventas-productos'
    | '/_layout/reportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/clientes': {
      id: '/_layout/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof LayoutClientesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compras': {
      id: '/_layout/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof LayoutComprasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configuracion': {
      id: '/_layout/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof LayoutConfiguracionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/multimedia': {
      id: '/_layout/multimedia'
      path: '/multimedia'
      fullPath: '/multimedia'
      preLoaderRoute: typeof LayoutMultimediaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pos': {
      id: '/_layout/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof LayoutPosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usuarios': {
      id: '/_layout/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof LayoutUsuariosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ventas': {
      id: '/_layout/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof LayoutVentasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/login/$tenantSlug': {
      id: '/login/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/login/$tenantSlug'
      preLoaderRoute: typeof LoginTenantSlugRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_layout/cajas/historial': {
      id: '/_layout/cajas/historial'
      path: '/cajas/historial'
      fullPath: '/cajas/historial'
      preLoaderRoute: typeof LayoutCajasHistorialRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cajas/registradoras': {
      id: '/_layout/cajas/registradoras'
      path: '/cajas/registradoras'
      fullPath: '/cajas/registradoras'
      preLoaderRoute: typeof LayoutCajasRegistradorasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventario/crear': {
      id: '/_layout/inventario/crear'
      path: '/inventario/crear'
      fullPath: '/inventario/crear'
      preLoaderRoute: typeof LayoutInventarioCrearRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventario/lotes': {
      id: '/_layout/inventario/lotes'
      path: '/inventario/lotes'
      fullPath: '/inventario/lotes'
      preLoaderRoute: typeof LayoutInventarioLotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventario/productos': {
      id: '/_layout/inventario/productos'
      path: '/inventario/productos'
      fullPath: '/inventario/productos'
      preLoaderRoute: typeof LayoutInventarioProductosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes/': {
      id: '/_layout/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof LayoutReportesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes/costo-ventas': {
      id: '/_layout/reportes/costo-ventas'
      path: '/reportes/costo-ventas'
      fullPath: '/reportes/costo-ventas'
      preLoaderRoute: typeof LayoutReportesCostoVentasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes/existencias-valuadas': {
      id: '/_layout/reportes/existencias-valuadas'
      path: '/reportes/existencias-valuadas'
      fullPath: '/reportes/existencias-valuadas'
      preLoaderRoute: typeof LayoutReportesExistenciasValuadasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes/ventas-productos': {
      id: '/_layout/reportes/ventas-productos'
      path: '/reportes/ventas-productos'
      fullPath: '/reportes/ventas-productos'
      preLoaderRoute: typeof LayoutReportesVentasProductosRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutClientesRoute: typeof LayoutClientesRoute
  LayoutComprasRoute: typeof LayoutComprasRoute
  LayoutConfiguracionRoute: typeof LayoutConfiguracionRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutMultimediaRoute: typeof LayoutMultimediaRoute
  LayoutPosRoute: typeof LayoutPosRoute
  LayoutUsuariosRoute: typeof LayoutUsuariosRoute
  LayoutVentasRoute: typeof LayoutVentasRoute
  LayoutCajasHistorialRoute: typeof LayoutCajasHistorialRoute
  LayoutCajasRegistradorasRoute: typeof LayoutCajasRegistradorasRoute
  LayoutInventarioCrearRoute: typeof LayoutInventarioCrearRoute
  LayoutInventarioLotesRoute: typeof LayoutInventarioLotesRoute
  LayoutInventarioProductosRoute: typeof LayoutInventarioProductosRoute
  LayoutReportesCostoVentasRoute: typeof LayoutReportesCostoVentasRoute
  LayoutReportesExistenciasValuadasRoute: typeof LayoutReportesExistenciasValuadasRoute
  LayoutReportesVentasProductosRoute: typeof LayoutReportesVentasProductosRoute
  LayoutReportesIndexRoute: typeof LayoutReportesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClientesRoute: LayoutClientesRoute,
  LayoutComprasRoute: LayoutComprasRoute,
  LayoutConfiguracionRoute: LayoutConfiguracionRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutMultimediaRoute: LayoutMultimediaRoute,
  LayoutPosRoute: LayoutPosRoute,
  LayoutUsuariosRoute: LayoutUsuariosRoute,
  LayoutVentasRoute: LayoutVentasRoute,
  LayoutCajasHistorialRoute: LayoutCajasHistorialRoute,
  LayoutCajasRegistradorasRoute: LayoutCajasRegistradorasRoute,
  LayoutInventarioCrearRoute: LayoutInventarioCrearRoute,
  LayoutInventarioLotesRoute: LayoutInventarioLotesRoute,
  LayoutInventarioProductosRoute: LayoutInventarioProductosRoute,
  LayoutReportesCostoVentasRoute: LayoutReportesCostoVentasRoute,
  LayoutReportesExistenciasValuadasRoute:
    LayoutReportesExistenciasValuadasRoute,
  LayoutReportesVentasProductosRoute: LayoutReportesVentasProductosRoute,
  LayoutReportesIndexRoute: LayoutReportesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LoginRouteChildren {
  LoginTenantSlugRoute: typeof LoginTenantSlugRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginTenantSlugRoute: LoginTenantSlugRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
